[package]
name = "async_tokio"
version = "0.0.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[dependencies]
boxfnonce = "*"
log = "0.3"
net2 = "0.2"
libc = "0.2"
lazy_static = "0.2"
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

#tokio-signal = "*"
tokio-signal = { git = "https://github.com/alexcrichton/tokio-signal.git" }
#tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
#tokio-io = { git = "https://github.com/tokio-rs/tokio-io" }

[dependencies.cpython]
git = "https://github.com/fafhrd91/rust-cpython.git"
#path = "../tokio/rust-cpython"
