[package]
name = "async_tokio"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[dependencies]
boxfnonce = "*"
log = "0.3"
net2 = "0.2"
libc = "0.2"
lazy_static = "0.2"
futures="0.1"
bytes = { git = "https://github.com/carllerche/bytes.git" }
tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
tokio-io = { git = "https://github.com/tokio-rs/tokio-io" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }

#dns-lookup = "0.2"
#dns-lookup = { git = "https://github.com/fafhrd91/dns-lookup.git" }
#dns-lookup = { path = "../../tokio/dns-lookup" }

[dependencies.cpython]
git = "https://github.com/fafhrd91/rust-cpython.git"
default-features = false

[lib]
crate-type = ["cdylib"]
